---
features:
  basicAuth: true
  oidcAuth: true
  defaultBucket: false

redis:
  image:
    registry: docker.io
  replica:
    persistence:
      enabled: false
  sentinel:
    image:
      registry: docker.io
    persistence:
      enabled: false
