---
features:
  basicAuth: true
  oidcAuth: true
  defaultBucket: false

redis:
  image:
    registry: artifacts.developer.gov.bc.ca/docker-remote
  replica:
    persistence:
      enabled: false
  sentinel:
    image:
      registry: artifacts.developer.gov.bc.ca/docker-remote
    persistence:
      enabled: false
